# simple
# services:
#   nginx:
#     image: nginx:alpine
#     ports:
#       - "8080:80" # Akses via localhost:8080, agar tidak conflict dengan nginx local
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro # copy local nginx config file ke dalam nginx
#       - ./html:/usr/share/nginx/html:ro # copy file html ke nginx
#     extra_hosts:
#       - "host.docker.internal:host-gateway" # agar bisa reverse proxy ke ip local os (backend golangnya)

# virdan nginx
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.virdan.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./html:/usr/share/nginx/html:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
