events {}
# Block wajib ada di nginx.conf, mengatur koneksi level low
# Dikosongkan = pakai default semua

http {
# Semua konfigurasi HTTP ada di dalam block ini

    server {
    # Satu server block = satu virtual host / satu domain
    # Bisa punya banyak server block untuk banyak domain
    
        listen 80;
        # Nginx listen di port 80 di dalam container
        
        server_name localhost;
        # Domain yang di-handle server block ini
        # Kalau request datang dengan Host header = localhost, block ini yang handle

        location / {
        # Cocokkan semua request yang URL-nya dimulai dengan /
        
            root /usr/share/nginx/html;
            # Cari file di folder ini
            
            index index.html;
            # Kalau request ke /, serve file index.html
        }

        location /api/ {
        # Cocokkan request yang URL-nya dimulai dengan /api/
        # Lebih spesifik dari location / , jadi ini yang diprioritaskan untuk /api/*
        
            proxy_pass http://host.docker.internal:8081;
            # Forward request ke Go backend di OS host port 8081
            
            proxy_set_header Host $host;
            # Kirim header Host asli dari client ke backend
            # $host = variable Nginx berisi nilai Host header dari request
            
            proxy_set_header X-Real-IP $remote_addr;
            # Kirim IP asli client ke backend
            # $remote_addr = IP yang konek ke Nginx
            # Tanpa ini, backend hanya lihat IP Nginx, bukan IP user asli
            
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # Header standar untuk chain proxy
            # Isi IP semua proxy yang dilalui request, termasuk IP client asli
            
            proxy_set_header X-Forwarded-Proto $scheme;
            # Kirim protokol asli (http/https) ke backend
            # $scheme = "http" atau "https"
            # Berguna agar backend tahu apakah request aslinya HTTPS atau bukan
        }
    }
}